### PR TITLE
Reduce binary size by excluding unused plugins

### PR DESCRIPTION
**Pull request by samoen**
## What are we doing?

We are shrinking the binary size of telegraf builds by excluding plugins we do not use. See [https://github.com/omc/shipit-telegraf/issues/27](https://github.com/omc/shipit-telegraf/issues/27)

I also added a GitHub Action to ensure changes we make to the repo still successfully builds a binary. 

A `go test` step could also be added - however currently many tests assume all plugins are imported so it would require putting `testing.T.skip()` in most of the plugin tests.

Closes omc/shipit-telegraf#27

### CODE REVIEW

**Comment by drusellers** [comment]
Curious, what was the reduction?

**Comment by drusellers** [comment]
> On first pass I see the size of the binary reduced from 70MB to 13MB by commenting out the import statements of unused plugins. So, nice!

Also, closes https://github.com/omc/shipit-telegraf/issues/27

**Comment by samoen** [comment]
> > On first pass I see the size of the binary reduced from 70MB to 13MB by commenting out the import statements of unused plugins. So, nice!
> 
> Also, closes [omc/shipit-telegraf#27](https://github.com/omc/shipit-telegraf/issues/27)

Looks like closing keywords don't work if the PR is in a different repo to the issue

**Comment by samoen** [comment]
Closed in favour of rebasing to v1.20.4 and squashing all omc's changes into one commit, see https://github.com/omc/telegraf/pull/4

**Pull request closed without merging**
